# Generated by Django 6.0.2 on 2026-02-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admission_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('current_class', models.CharField(max_length=100)),
            ],
        ),
    ]
